[package]
name = "windows-kernel-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winresult = "0.1.3"

[build-dependencies]
bindgen = "0.69.1"
thiserror = "1.0.40"
winreg = "0.50.0"
cc = "1.0"
