[package]
name = "ndis-rs"
version = "0.1.0"
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows-kernel-sys.workspace = true
static_assertions.workspace = true
