[env]
VC_BUILD_DIR="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"

DRIVER_VERSION="*"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
TARGET_ARCH = { source = "${CARGO_MAKE_RUST_TARGET_TRIPLE}", default_value = "unsupported", mapping = { "i686-pc-windows-msvc" = "x86", "x86_64-pc-windows-msvc" = "amd64", "aarch64-pc-windows-msvc" = "arm64" } }
TARGET_BASE_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}\\${CARGO_MAKE_RUST_TARGET_TRIPLE}"
# From https://github.com/microsoft/windows-drivers-rs/blob/15a3c50a08d83965ebbf11a8dc62e03a0c131e03/rust-driver-makefile.toml#L11-L12
TARGET_DIR = { source = "${CARGO_MAKE_CARGO_PROFILE}", default_value = "${TARGET_BASE_DIR}\\${CARGO_MAKE_CARGO_PROFILE}", mapping = { "dev" = "${TARGET_BASE_DIR}\\debug" } }

# Platform for executing tools
Platform = "x86"
# Load VS DevEnv (x86 since that's where inf2cat is)
Wdk_WindowsSdkVerBinPath = { script = ['call "%VC_BUILD_DIR%" %Platform%', 'echo %WindowsSdkVerBinPath%\%Platform%'], depends_on = ["VC_BUILD_DIR", "Platform"] }
Wdk_WindowsSdkVerToolPath = { script = ['call "%VC_BUILD_DIR%" %Platform%', 'echo %WindowsSdkDir%\Tools\%WindowsSDKVersion%\%Platform%'], depends_on = ["VC_BUILD_DIR", "Platform"] }

[tasks.build]
env = { "RUSTFLAGS" = "-Clinker-plugin-lto -Clinker=lld-link -Clink-arg=-fuse-ld=lld-link" }
# Specify the target triple so that -Cprefer-dynamic doesn't conflict with -Clinker-plugin-lto while building proc macros
args = ["build", "--target", "${CARGO_MAKE_RUST_TARGET_TRIPLE}"]

[tasks.rename]
dependencies = ["build"]
cwd = "${TARGET_DIR}"
script = '''
if exist %CARGO_MAKE_CRATE_FS_NAME%.sys (
  del %CARGO_MAKE_CRATE_FS_NAME%.sys
)
rename %CARGO_MAKE_CRATE_FS_NAME%.dll %CARGO_MAKE_CRATE_FS_NAME%.sys
'''

[tasks.make-dist]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='if not exist dist\%CARGO_MAKE_CRATE_NAME% ( mkdir dist\%CARGO_MAKE_CRATE_NAME% )'

[tasks.copysys]
dependencies = ["make-dist", "rename"]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='''
copy %TARGET_DIR%\%CARGO_MAKE_CRATE_FS_NAME%.sys dist\%CARGO_MAKE_CRATE_NAME%\
copy %TARGET_DIR%\%CARGO_MAKE_CRATE_FS_NAME%.pdb dist\%CARGO_MAKE_CRATE_NAME%\
'''

[tasks.stampinf]
dependencies = ["make-dist"]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='''
copy "%CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY%\%CARGO_MAKE_CRATE_FS_NAME%.inx" "dist\%CARGO_MAKE_CRATE_NAME%\%CARGO_MAKE_CRATE_FS_NAME%.inf"
"%Wdk_WindowsSdkVerBinPath%\stampinf.exe" -f dist\%CARGO_MAKE_CRATE_NAME%\%CARGO_MAKE_CRATE_FS_NAME%.inf -a %TARGET_ARCH% -d %DRIVER_VERSION% -v %DRIVER_VERSION% -k 1.31 -x
'''

[tasks.infverif]
dependencies = ["stampinf"]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='''
"%Wdk_WindowsSdkVerToolPath%\infverif.exe" /v /w "dist\%CARGO_MAKE_CRATE_NAME%\%CARGO_MAKE_CRATE_FS_NAME%.inf" /msft
'''

[tasks.inf2cat]
dependencies = ["stampinf"]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='''
"%Wdk_WindowsSdkVerBinPath%\inf2cat.exe" /driver:dist\%CARGO_MAKE_CRATE_NAME%\ /os:10_x64
'''

[tasks.dist]
dependencies = ["copysys", "inf2cat", "infverif"]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='''
@rem Make a self-signed cert
if not exist DriverCertificate.cer (
  makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer
) else (
  echo Certificate already exists.
)

@rem And sign the driver
"%Wdk_WindowsSdkVerBinPath%\signtool.exe" sign /debug /a /ph /v /s PrivateCertStore /n DriverCertificate /fd certHash /t http://timestamp.digicert.com dist/%CARGO_MAKE_CRATE_NAME%/%CARGO_MAKE_CRATE_FS_NAME%.sys dist/%CARGO_MAKE_CRATE_NAME%/*.cat

copy DriverCertificate.cer dist\%CARGO_MAKE_CRATE_NAME%\
'''
