[env]
VC_BUILD_DIR="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"

DRIVER_VERSION="*"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[env.development]
TARGET_PATH = "target\\debug"

[env.production]
TARGET_PATH = "target\\release"
BUILD_RELEASE = "--release"

[tasks.build-driver]
script = '''
cargo b %BUILD_FLAGS%
'''

[tasks.rename]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/${TARGET_PATH}"
script = '''
if exist %CARGO_MAKE_CRATE_FS_NAME%.sys (
  del %CARGO_MAKE_CRATE_FS_NAME%.sys
)
rename %CARGO_MAKE_CRATE_FS_NAME%.dll %CARGO_MAKE_CRATE_FS_NAME%.sys
'''

[tasks.make-dist]
ignore_errors = true
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='mkdir dist'

[tasks.stampinf]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='''
@rem Load VS DevEnv
call "%VC_BUILD_DIR%" x64

copy driver\%CARGO_MAKE_CRATE_NAME%\ndisprot.inf %TARGET_PATH%
stampinf -f %TARGET_PATH%\ndisprot.inf -a amd64 -d * -v %DRIVER_VERSION% -k 1.31 -x
'''

[tasks.dist]
dependencies = ["build-driver", "rename", "stampinf", "make-dist"]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script='''
copy %TARGET_PATH%\%CARGO_MAKE_CRATE_FS_NAME%.sys dist\
copy %TARGET_PATH%\%CARGO_MAKE_CRATE_FS_NAME%.pdb dist\
copy %TARGET_PATH%\ndisprot.inf dist\

@rem for some reason, inf2cat is not in the x64 paths
call "%VC_BUILD_DIR%" x86

inf2cat /driver:dist\ /os:10_x64

@rem Make a self-signed cert
if not exist DriverCertificate.cer ( makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer ) else ( echo Certificate already exists. )

@rem And sign the driver
signtool sign /debug /a /ph /v /s PrivateCertStore /n DriverCertificate /fd sha1 /t http://timestamp.digicert.com dist/%CARGO_MAKE_CRATE_FS_NAME%.sys dist/*.cat

copy DriverCertificate.cer dist\
'''
